// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENT_CLIENT_H_
#define FLATBUFFERS_GENERATED_CLIENT_CLIENT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace Client {

struct TestMessage;
struct TestMessageBuilder;

struct Body;
struct BodyBuilder;

enum Protocol : uint8_t {
  Protocol_NONE = 0,
  Protocol_TestMessage = 1,
  Protocol_MIN = Protocol_NONE,
  Protocol_MAX = Protocol_TestMessage
};

inline const Protocol (&EnumValuesProtocol())[2] {
  static const Protocol values[] = {
    Protocol_NONE,
    Protocol_TestMessage
  };
  return values;
}

inline const char * const *EnumNamesProtocol() {
  static const char * const names[3] = {
    "NONE",
    "TestMessage",
    nullptr
  };
  return names;
}

inline const char *EnumNameProtocol(Protocol e) {
  if (::flatbuffers::IsOutRange(e, Protocol_NONE, Protocol_TestMessage)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesProtocol()[index];
}

template<typename T> struct ProtocolTraits {
  static const Protocol enum_value = Protocol_NONE;
};

template<> struct ProtocolTraits<Client::TestMessage> {
  static const Protocol enum_value = Protocol_TestMessage;
};

bool VerifyProtocol(::flatbuffers::Verifier &verifier, const void *obj, Protocol type);
bool VerifyProtocolVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct TestMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TestMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TITLE = 4,
    VT_BODY = 6
  };
  const ::flatbuffers::String *title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TITLE);
  }
  const ::flatbuffers::String *body() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BODY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TITLE) &&
           verifier.VerifyString(title()) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyString(body()) &&
           verifier.EndTable();
  }
};

struct TestMessageBuilder {
  typedef TestMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_title(::flatbuffers::Offset<::flatbuffers::String> title) {
    fbb_.AddOffset(TestMessage::VT_TITLE, title);
  }
  void add_body(::flatbuffers::Offset<::flatbuffers::String> body) {
    fbb_.AddOffset(TestMessage::VT_BODY, body);
  }
  explicit TestMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TestMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TestMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TestMessage> CreateTestMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> title = 0,
    ::flatbuffers::Offset<::flatbuffers::String> body = 0) {
  TestMessageBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_title(title);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TestMessage> CreateTestMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *title = nullptr,
    const char *body = nullptr) {
  auto title__ = title ? _fbb.CreateString(title) : 0;
  auto body__ = body ? _fbb.CreateString(body) : 0;
  return Client::CreateTestMessage(
      _fbb,
      title__,
      body__);
}

struct Body FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BodyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_TYPE = 4,
    VT_BODY = 6
  };
  Client::Protocol body_type() const {
    return static_cast<Client::Protocol>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const Client::TestMessage *body_as_TestMessage() const {
    return body_type() == Client::Protocol_TestMessage ? static_cast<const Client::TestMessage *>(body()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyProtocol(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Client::TestMessage *Body::body_as<Client::TestMessage>() const {
  return body_as_TestMessage();
}

struct BodyBuilder {
  typedef Body Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_type(Client::Protocol body_type) {
    fbb_.AddElement<uint8_t>(Body::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(Body::VT_BODY, body);
  }
  explicit BodyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Body> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Body>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Body> CreateBody(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Client::Protocol body_type = Client::Protocol_NONE,
    ::flatbuffers::Offset<void> body = 0) {
  BodyBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  return builder_.Finish();
}

inline bool VerifyProtocol(::flatbuffers::Verifier &verifier, const void *obj, Protocol type) {
  switch (type) {
    case Protocol_NONE: {
      return true;
    }
    case Protocol_TestMessage: {
      auto ptr = reinterpret_cast<const Client::TestMessage *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyProtocolVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyProtocol(
        verifier,  values->Get(i), types->GetEnum<Protocol>(i))) {
      return false;
    }
  }
  return true;
}

inline const Client::Body *GetBody(const void *buf) {
  return ::flatbuffers::GetRoot<Client::Body>(buf);
}

inline const Client::Body *GetSizePrefixedBody(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Client::Body>(buf);
}

inline bool VerifyBodyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Client::Body>(nullptr);
}

inline bool VerifySizePrefixedBodyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Client::Body>(nullptr);
}

inline void FinishBodyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Client::Body> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBodyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Client::Body> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Client

#endif  // FLATBUFFERS_GENERATED_CLIENT_CLIENT_H_
