// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SERVERTEST_SERVERTEST_H_
#define FLATBUFFERS_GENERATED_SERVERTEST_SERVERTEST_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace ServerTest {

struct Test;
struct TestBuilder;

struct Body;
struct BodyBuilder;

enum Protocol : uint8_t {
  Protocol_NONE = 0,
  Protocol_Test = 1,
  Protocol_MIN = Protocol_NONE,
  Protocol_MAX = Protocol_Test
};

inline const Protocol (&EnumValuesProtocol())[2] {
  static const Protocol values[] = {
    Protocol_NONE,
    Protocol_Test
  };
  return values;
}

inline const char * const *EnumNamesProtocol() {
  static const char * const names[3] = {
    "NONE",
    "Test",
    nullptr
  };
  return names;
}

inline const char *EnumNameProtocol(Protocol e) {
  if (::flatbuffers::IsOutRange(e, Protocol_NONE, Protocol_Test)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesProtocol()[index];
}

template<typename T> struct ProtocolTraits {
  static const Protocol enum_value = Protocol_NONE;
};

template<> struct ProtocolTraits<ServerTest::Test> {
  static const Protocol enum_value = Protocol_Test;
};

bool VerifyProtocol(::flatbuffers::Verifier &verifier, const void *obj, Protocol type);
bool VerifyProtocolVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct Test FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE = 4
  };
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct TestBuilder {
  typedef Test Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(Test::VT_MESSAGE, message);
  }
  explicit TestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Test> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Test>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Test> CreateTest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  TestBuilder builder_(_fbb);
  builder_.add_message(message);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Test> CreateTestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return ServerTest::CreateTest(
      _fbb,
      message__);
}

struct Body FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BodyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_TYPE = 4,
    VT_BODY = 6
  };
  ServerTest::Protocol body_type() const {
    return static_cast<ServerTest::Protocol>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const ServerTest::Test *body_as_Test() const {
    return body_type() == ServerTest::Protocol_Test ? static_cast<const ServerTest::Test *>(body()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyProtocol(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

template<> inline const ServerTest::Test *Body::body_as<ServerTest::Test>() const {
  return body_as_Test();
}

struct BodyBuilder {
  typedef Body Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_type(ServerTest::Protocol body_type) {
    fbb_.AddElement<uint8_t>(Body::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(Body::VT_BODY, body);
  }
  explicit BodyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Body> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Body>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Body> CreateBody(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ServerTest::Protocol body_type = ServerTest::Protocol_NONE,
    ::flatbuffers::Offset<void> body = 0) {
  BodyBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  return builder_.Finish();
}

inline bool VerifyProtocol(::flatbuffers::Verifier &verifier, const void *obj, Protocol type) {
  switch (type) {
    case Protocol_NONE: {
      return true;
    }
    case Protocol_Test: {
      auto ptr = reinterpret_cast<const ServerTest::Test *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyProtocolVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyProtocol(
        verifier,  values->Get(i), types->GetEnum<Protocol>(i))) {
      return false;
    }
  }
  return true;
}

inline const ServerTest::Body *GetBody(const void *buf) {
  return ::flatbuffers::GetRoot<ServerTest::Body>(buf);
}

inline const ServerTest::Body *GetSizePrefixedBody(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ServerTest::Body>(buf);
}

inline bool VerifyBodyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ServerTest::Body>(nullptr);
}

inline bool VerifySizePrefixedBodyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ServerTest::Body>(nullptr);
}

inline void FinishBodyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ServerTest::Body> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBodyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ServerTest::Body> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ServerTest

#endif  // FLATBUFFERS_GENERATED_SERVERTEST_SERVERTEST_H_
