// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SERVER_H_
#define FLATBUFFERS_GENERATED_SERVER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

#include "server_common_generated.h"
#include "server_test_generated.h"

struct ServerPacketBody;
struct ServerPacketBodyBuilder;

enum ServerPacket : uint8_t {
  ServerPacket_NONE = 0,
  ServerPacket_ServerCommon_Body = 1,
  ServerPacket_ServerTest_Body = 2,
  ServerPacket_MIN = ServerPacket_NONE,
  ServerPacket_MAX = ServerPacket_ServerTest_Body
};

inline const ServerPacket (&EnumValuesServerPacket())[3] {
  static const ServerPacket values[] = {
    ServerPacket_NONE,
    ServerPacket_ServerCommon_Body,
    ServerPacket_ServerTest_Body
  };
  return values;
}

inline const char * const *EnumNamesServerPacket() {
  static const char * const names[4] = {
    "NONE",
    "ServerCommon_Body",
    "ServerTest_Body",
    nullptr
  };
  return names;
}

inline const char *EnumNameServerPacket(ServerPacket e) {
  if (::flatbuffers::IsOutRange(e, ServerPacket_NONE, ServerPacket_ServerTest_Body)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesServerPacket()[index];
}

template<typename T> struct ServerPacketTraits {
  static const ServerPacket enum_value = ServerPacket_NONE;
};

template<> struct ServerPacketTraits<ServerCommon::Body> {
  static const ServerPacket enum_value = ServerPacket_ServerCommon_Body;
};

template<> struct ServerPacketTraits<ServerTest::Body> {
  static const ServerPacket enum_value = ServerPacket_ServerTest_Body;
};

bool VerifyServerPacket(::flatbuffers::Verifier &verifier, const void *obj, ServerPacket type);
bool VerifyServerPacketVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct ServerPacketBody FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerPacketBodyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_TYPE = 4,
    VT_BODY = 6
  };
  ServerPacket body_type() const {
    return static_cast<ServerPacket>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const ServerCommon::Body *body_as_ServerCommon_Body() const {
    return body_type() == ServerPacket_ServerCommon_Body ? static_cast<const ServerCommon::Body *>(body()) : nullptr;
  }
  const ServerTest::Body *body_as_ServerTest_Body() const {
    return body_type() == ServerPacket_ServerTest_Body ? static_cast<const ServerTest::Body *>(body()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyServerPacket(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

template<> inline const ServerCommon::Body *ServerPacketBody::body_as<ServerCommon::Body>() const {
  return body_as_ServerCommon_Body();
}

template<> inline const ServerTest::Body *ServerPacketBody::body_as<ServerTest::Body>() const {
  return body_as_ServerTest_Body();
}

struct ServerPacketBodyBuilder {
  typedef ServerPacketBody Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_type(ServerPacket body_type) {
    fbb_.AddElement<uint8_t>(ServerPacketBody::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(ServerPacketBody::VT_BODY, body);
  }
  explicit ServerPacketBodyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerPacketBody> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerPacketBody>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerPacketBody> CreateServerPacketBody(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ServerPacket body_type = ServerPacket_NONE,
    ::flatbuffers::Offset<void> body = 0) {
  ServerPacketBodyBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  return builder_.Finish();
}

inline bool VerifyServerPacket(::flatbuffers::Verifier &verifier, const void *obj, ServerPacket type) {
  switch (type) {
    case ServerPacket_NONE: {
      return true;
    }
    case ServerPacket_ServerCommon_Body: {
      auto ptr = reinterpret_cast<const ServerCommon::Body *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ServerPacket_ServerTest_Body: {
      auto ptr = reinterpret_cast<const ServerTest::Body *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyServerPacketVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyServerPacket(
        verifier,  values->Get(i), types->GetEnum<ServerPacket>(i))) {
      return false;
    }
  }
  return true;
}

inline const ServerPacketBody *GetServerPacketBody(const void *buf) {
  return ::flatbuffers::GetRoot<ServerPacketBody>(buf);
}

inline const ServerPacketBody *GetSizePrefixedServerPacketBody(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ServerPacketBody>(buf);
}

inline bool VerifyServerPacketBodyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ServerPacketBody>(nullptr);
}

inline bool VerifySizePrefixedServerPacketBodyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ServerPacketBody>(nullptr);
}

inline void FinishServerPacketBodyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ServerPacketBody> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedServerPacketBodyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ServerPacketBody> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_SERVER_H_
