// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SERVERCOMMON_SERVERCOMMON_H_
#define FLATBUFFERS_GENERATED_SERVERCOMMON_SERVERCOMMON_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace ServerCommon {

struct Activation;
struct ActivationBuilder;

struct Shutdown;
struct ShutdownBuilder;

struct Body;
struct BodyBuilder;

enum Protocol : uint8_t {
  Protocol_NONE = 0,
  Protocol_Activation = 1,
  Protocol_Shutdown = 2,
  Protocol_MIN = Protocol_NONE,
  Protocol_MAX = Protocol_Shutdown
};

inline const Protocol (&EnumValuesProtocol())[3] {
  static const Protocol values[] = {
    Protocol_NONE,
    Protocol_Activation,
    Protocol_Shutdown
  };
  return values;
}

inline const char * const *EnumNamesProtocol() {
  static const char * const names[4] = {
    "NONE",
    "Activation",
    "Shutdown",
    nullptr
  };
  return names;
}

inline const char *EnumNameProtocol(Protocol e) {
  if (::flatbuffers::IsOutRange(e, Protocol_NONE, Protocol_Shutdown)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesProtocol()[index];
}

template<typename T> struct ProtocolTraits {
  static const Protocol enum_value = Protocol_NONE;
};

template<> struct ProtocolTraits<ServerCommon::Activation> {
  static const Protocol enum_value = Protocol_Activation;
};

template<> struct ProtocolTraits<ServerCommon::Shutdown> {
  static const Protocol enum_value = Protocol_Shutdown;
};

bool VerifyProtocol(::flatbuffers::Verifier &verifier, const void *obj, Protocol type);
bool VerifyProtocolVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct Activation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ActivationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODULETYPE = 4,
    VT_SERVERID = 6,
    VT_SERVERGROUPID = 8
  };
  uint16_t moduleType() const {
    return GetField<uint16_t>(VT_MODULETYPE, 0);
  }
  uint16_t serverId() const {
    return GetField<uint16_t>(VT_SERVERID, 0);
  }
  uint16_t serverGroupId() const {
    return GetField<uint16_t>(VT_SERVERGROUPID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_MODULETYPE, 2) &&
           VerifyField<uint16_t>(verifier, VT_SERVERID, 2) &&
           VerifyField<uint16_t>(verifier, VT_SERVERGROUPID, 2) &&
           verifier.EndTable();
  }
};

struct ActivationBuilder {
  typedef Activation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_moduleType(uint16_t moduleType) {
    fbb_.AddElement<uint16_t>(Activation::VT_MODULETYPE, moduleType, 0);
  }
  void add_serverId(uint16_t serverId) {
    fbb_.AddElement<uint16_t>(Activation::VT_SERVERID, serverId, 0);
  }
  void add_serverGroupId(uint16_t serverGroupId) {
    fbb_.AddElement<uint16_t>(Activation::VT_SERVERGROUPID, serverGroupId, 0);
  }
  explicit ActivationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Activation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Activation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Activation> CreateActivation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t moduleType = 0,
    uint16_t serverId = 0,
    uint16_t serverGroupId = 0) {
  ActivationBuilder builder_(_fbb);
  builder_.add_serverGroupId(serverGroupId);
  builder_.add_serverId(serverId);
  builder_.add_moduleType(moduleType);
  return builder_.Finish();
}

struct Shutdown FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ShutdownBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ShutdownBuilder {
  typedef Shutdown Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ShutdownBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Shutdown> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Shutdown>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Shutdown> CreateShutdown(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ShutdownBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Body FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BodyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_TYPE = 4,
    VT_BODY = 6
  };
  ServerCommon::Protocol body_type() const {
    return static_cast<ServerCommon::Protocol>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const ServerCommon::Activation *body_as_Activation() const {
    return body_type() == ServerCommon::Protocol_Activation ? static_cast<const ServerCommon::Activation *>(body()) : nullptr;
  }
  const ServerCommon::Shutdown *body_as_Shutdown() const {
    return body_type() == ServerCommon::Protocol_Shutdown ? static_cast<const ServerCommon::Shutdown *>(body()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyProtocol(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

template<> inline const ServerCommon::Activation *Body::body_as<ServerCommon::Activation>() const {
  return body_as_Activation();
}

template<> inline const ServerCommon::Shutdown *Body::body_as<ServerCommon::Shutdown>() const {
  return body_as_Shutdown();
}

struct BodyBuilder {
  typedef Body Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_type(ServerCommon::Protocol body_type) {
    fbb_.AddElement<uint8_t>(Body::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(Body::VT_BODY, body);
  }
  explicit BodyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Body> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Body>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Body> CreateBody(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ServerCommon::Protocol body_type = ServerCommon::Protocol_NONE,
    ::flatbuffers::Offset<void> body = 0) {
  BodyBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  return builder_.Finish();
}

inline bool VerifyProtocol(::flatbuffers::Verifier &verifier, const void *obj, Protocol type) {
  switch (type) {
    case Protocol_NONE: {
      return true;
    }
    case Protocol_Activation: {
      auto ptr = reinterpret_cast<const ServerCommon::Activation *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Protocol_Shutdown: {
      auto ptr = reinterpret_cast<const ServerCommon::Shutdown *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyProtocolVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyProtocol(
        verifier,  values->Get(i), types->GetEnum<Protocol>(i))) {
      return false;
    }
  }
  return true;
}

inline const ServerCommon::Body *GetBody(const void *buf) {
  return ::flatbuffers::GetRoot<ServerCommon::Body>(buf);
}

inline const ServerCommon::Body *GetSizePrefixedBody(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ServerCommon::Body>(buf);
}

inline bool VerifyBodyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ServerCommon::Body>(nullptr);
}

inline bool VerifySizePrefixedBodyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ServerCommon::Body>(nullptr);
}

inline void FinishBodyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ServerCommon::Body> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBodyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ServerCommon::Body> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ServerCommon

#endif  // FLATBUFFERS_GENERATED_SERVERCOMMON_SERVERCOMMON_H_
